found out why the error for my file name was not working. Also updated code.
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Users\Zairick\source\repos\Assignment1.1\Assignment1.1\bin\Debug\netcoreapp2.2\ \Users\Zairick\Desktop\USM\Fall 2019\COS 470\Projects\Assignment 1\dollarWords.txt'.'

it's because it was way too long, I went down to the root of C and made a file there.